#include "arduino_secrets.h"
/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
  https://create.arduino.cc/cloud/things/c746fcf7-ae40-4313-bc14-8dd17372d0ab

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudAcceleration accx;
  CloudAcceleration accy;
  CloudAcceleration accz;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <Arduino_LSM6DS3.h>

float x, y, z;
float xg,yg,zg;

void setup() {
  Serial.begin(9600);
  delay(1500);

  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  if (!IMU.begin()) {
    Serial.println("Failed to initialize IMU!");
    while (1);
  }

}

void loop() {
  ArduinoCloud.update();

  if (IMU.accelerationAvailable()) {
    IMU.readAcceleration(x, y, z);

    Serial.print("Acc,");
    Serial.print(x*100);
    Serial.print(',');
    Serial.print(y*100);
    Serial.print(',');
    Serial.print(z*100);
    accx=x*100;
    accy=y*100;
    accz=z*100;

  }

    if (IMU.gyroscopeAvailable()) {
    IMU.readGyroscope(xg, yg, zg);
    Serial.print(",Gyro,");
    Serial.print(xg);
    Serial.print(',');
    Serial.print(yg);
    Serial.print(',');
    Serial.print(zg);
    Serial.println();
  }

  delay(50);
}
